monday = c(5,4,5,7)
tuesday = c(4,5,3,2)
wednesday = c(4,3,4,5)
thursday = c(4,4,3,2)
x =c(monday,tuesday,wednesday,thursday)
group = c(rep("monday",4) ,rep("tuesday",4) ,rep("wednesday",4) ,rep("thursday",4))
dat = data.frame(x,group)
print(dat)
av = aov(x~as.factor(group))
print(summary(av))
